### ISSUE TITLE
Make letter

### ISSUE THREAD

**Issue by IvanNChiu** [IT171/Student-Evaluation-and-Monitoring-System#4]
letter to sir omen hahaha

**Comment by kikateee** [comment]
omg!!!!! na amaze ko ani lage ay <3 so dre ko magsend og letter na kuya? sge kuya, ipass nko ugma jd. ako sa isure ang name ni sir omen.

**Comment by IvanNChiu** [comment]
Sure, ibutang sa imong folder ang letter.
